# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iOS-MyCode-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for iOS-MyCode-Example
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwiftMessages'

  target 'iOS-MyCode-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS-MyCode-ExampleUITests' do
    # Pods for testing
  end

end
